# Generated by Django 3.2.6 on 2021-08-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediatype',
            options={'verbose_name': 'Носитель', 'verbose_name_plural': 'Носители'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank='True', related_name='related_cart', to='musicshop.CartProduct', verbose_name='Продукты для корзины'),
        ),
    ]
